all:
	g++ main.cpp Controller.cpp Game.cpp GameWindow.cpp Reader.cpp RobotController.cpp UserController.cpp GTKController.cpp -o Text_Game_Engine_with_gtkmm `pkg-config gtkmm-3.0 --cflags --libs` --std=c++11
